# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://lyrics1874.github.io 
date_format: "ordinal"
title: lyrics1874 
subtitle: "Hello, 1874!"
description: "lyrics1874的个人博客"
keywords: 暂无 
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: lyrics1874
organization: 
organization_url: 
github_username: lyrics1874
location: Beijing, China
email: todo@todo.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lyrics1874/lyrics1874.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: lyrics1874
#    repo: blog-comments
#    oauth:
#        client_id: 14d5508528b7f37e2c23
#        client_secret: d6f1d17074fc704598ad91ca77f9d05ff7e288f4
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: lyrics1874
    repo: blog-comments
    clientID: 14d5508528b7f37e2c23
    clientSecret: d6f1d17074fc704598ad91ca77f9d05ff7e288f4
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
